### ISSUE TITLE
PartnerTalk

### ISSUE THREAD

**Issue by SunbossRS** [SunbossRS/Miniworld-WakuangCrx#5]
@sctop  
你可以帮忙加上一个文件吗  
等我抓到drawerror.exe(点开该exe后会在鼠标经过的地方画x)和一个抖动鼠标的exe包后可以把它们加到那个exe里吗，我在源码bat里面的文本有个CertUtil的命令是吧base64的一个exe用-decode(编译文件转出来)的东西

**Comment by sctop** [comment]
certutil很坑爹的。我试过将MP3转换，后来看见文件内容我就直接崩溃了

**Comment by sctop** [comment]
超过50000行

**Comment by sctop** [comment]
我看到文件了

**Comment by SunbossRS** [comment]
那个visualstudio的c语言有文件转换吗

**Comment by sctop** [comment]
@SunbossRS 最主要的东西，就是先我们自行转换成base64，然后创建一个新文件并写内容进去，再用cmd命令

**Comment by SunbossRS** [comment]
yes

**Comment by sctop** [comment]
嗯，so

**Comment by sctop** [comment]
稍等一下为了防止某些傻X权限我要找到用户目录

**Comment by SunbossRS** [comment]
这样
<pre>
<code class="language-bat">
if exist C:\Users\%username%\ cd C:\Users\%username%\

if exist D:\Users\%username%\ cd D:\Users\%username%\

if exist E:\Users\%username%\ cd E:\Users\%username%\
</code>
</pre>
有些人把系统装在其他盘里

**Comment by SunbossRS** [comment]
这是batch
